# Testing different methods of convolution

In [138]:
import cv2
from scipy import signal as sig
import numpy as np

# Define Test Array

In [139]:
a = np.array([0,1,2,3,4,5,6,7,8,9,0,2,4,6,8,1,3,5,7,9,9,8,7,6,5], dtype=np.int16)
a = a.reshape(5,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 2 4 6 8]
 [1 3 5 7 9]
 [9 8 7 6 5]]


### Add Padding

In [140]:
a_padded = np.pad(a, 1, 'constant', constant_values=0)
print(a_padded)
print(a_padded.shape)

[[0 0 0 0 0 0 0]
 [0 0 1 2 3 4 0]
 [0 5 6 7 8 9 0]
 [0 0 2 4 6 8 0]
 [0 1 3 5 7 9 0]
 [0 9 8 7 6 5 0]
 [0 0 0 0 0 0 0]]
(7, 7)


# Scikit Image Convolution

In [141]:
def gradient_x(imggray):
    ##Sobel operator kernels.
    kernel_x = np.array([[-1, 0, 1],[-2, 0, 2],[-1, 0, 1]])
    return sig.convolve2d(imggray, kernel_x, mode='same')
def gradient_y(imggray):
    kernel_y = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
    return sig.convolve2d(imggray, kernel_y, mode='same')

In [142]:
x_grad = gradient_x(a)
print(x_grad)

[[ -8  -6  -6  -6  14]
 [-15 -10 -10 -10  25]
 [-13 -14 -14 -14  27]
 [-16 -10 -10 -10  26]
 [-19   0   0   0  19]]


# OpenCV Sobel Operation

In [143]:
ddepth = cv2.CV_16S
scale = 1
delta = 0
grad_x = cv2.Sobel(a, ddepth, 1, 0, ksize=3, scale=scale, delta=delta, borderType=cv2.BORDER_CONSTANT)
print(grad_x)

[[  8   6   6   6 -14]
 [ 15  10  10  10 -25]
 [ 13  14  14  14 -27]
 [ 16  10  10  10 -26]
 [ 19   0   0   0 -19]]


# Convolution Implementation from Scratch

In [144]:
#https://en.m.wikipedia.org/wiki/Kernel_(image_processing)

sobel_kernel_x = np.array([-1, 0, 1, -2, 0, 2, -1, 0, 1], dtype=np.int16).reshape(3,3)
sobel_kernel_y = np.array([1, 2, 1, 0, 0, 0, -1, -2, -1], dtype=np.int16).reshape(3,3)

kernel = sobel_kernel_x

kernel_size = kernel.shape[0]
print('kernel size: ' + str(kernel_size))
print('Kernel: ')
print(str(kernel))


acc= 0

def convolve(a):
    a = np.asarray(a)
    dest = np.zeros(shape=(a.shape[0]-2, a.shape[1]-2), dtype=np.int16)
    print('dest shape:' + str(dest.shape))
    row_size = dest.shape[0]
    col_size = dest.shape[1]
    print('dest row size: ' + str(dest.shape[0]) + ' dest col size: ' + str(dest.shape[1]))
    for i in range (row_size):
        for j in range (col_size):
            acc = 0          
            
            #print('[' + str(i) + '][' + str(j) + ']')
            #print('Convolution: [' + str(i) + '][' + str(j) + ']')
            
            for k in range (kernel.shape[0]):
                for l in range (kernel.shape[1]):
                    
                    #print('[' + str(k) + '][' + str(l) + ']')
                    #print('kernel element: ' + str(kernel[kernel_size-1-k][kernel_size-1-l]))
                    #print('a element: ' + str(a[i+k][j+l]))
                    
                    acc += kernel[kernel_size-1-k][kernel_size-1-l]*a[i+k][j+l]
                    
            #print('dest[' + str(i) + '][' + str(j) + ']')
            
            dest[i][j] = acc
    return dest
            


kernel size: 3
Kernel: 
[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]


In [145]:
res = convolve(a_padded)
print(res)

dest shape:(5, 5)
dest row size: 5 dest col size: 5
[[ -8  -6  -6  -6  14]
 [-15 -10 -10 -10  25]
 [-13 -14 -14 -14  27]
 [-16 -10 -10 -10  26]
 [-19   0   0   0  19]]
